# 8"""8                              eeeee  eeee 
# 8   8  eeee eeeee eeeee  eeeee     8   8     8 
# 82ee8e 8      8   8   8  8  82     82ee8     8 
# 82   8 82ee   82  8eee8e 8   8    82   82 eee8 
# 82   8 82     82  82   8 8   8    82   82 82    
# 82   8 82ee   82  82   8 82ee8    82eee82 82ee 
#                                                

# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.
#
#  ================================================================

$activeBorderColor = rgb(faa968)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

#=================================================================
#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 
