accent = "#827ece"
cursor = "#faf9f9"
foreground = "#faf9f9"
background = "#0e0e11"
selection_foreground = "#faf9f9"
selection_background = "#827ece"

color0 = "#0e0e11"
color1 = "#c9aaee"
color2 = "#7e83ce"
color3 = "#c5a8f0"
color4 = "#827ece"
color5 = "#c8aeea"
color6 = "#827ece"
color7 = "#faf9fa"
color8 = "#9b9bb0"
color9 = "#caa8f0"
color10 = "#7e82ce"
color11 = "#e3b5b5"
color12 = "#837ece"
color13 = "#c8aaee"
color14 = "#827ece"
color15 = "#faf9f9"
