#################
### AUTOSTART ###
#################

exec-once = uwsm-app hypridle
exec-once = wl-paste --type text --watch wl-copy --primary
exec-once = uwsm-app mako
exec-once = uwsm-app awww-daemon
exec-once = uwsm-app swayosd-server
exec-once = uwsm-app waybar
