###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = $terminal -e yazi
$browser = zen-browser
$qs = quickshell ipc call
$apps = $qs openApps handle
$menu = $qs openMenu handle
$editor = $terminal --title=nvim -e nvim
$emoji = $qs openEmojiPicker handle

xwayland {
  force_zero_scaling = true
}

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

# env = EDITOR,nvim
env = GDK_SCALE,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = WLR_RENDER_WITHOUT_EXT_BUFFER,1
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct

# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1

# GUM
env = GUM_CONFIRM_PROMPT_FOREGROUND,6       # Cyan
env = GUM_CONFIRM_SELECTED_FOREGROUND,0     # Black
env = GUM_CONFIRM_SELECTED_BACKGROUND,2     # Green
env = GUM_CONFIRM_UNSELECTED_FOREGROUND,7   # White
env = GUM_CONFIRM_UNSELECTED_BACKGROUND,8   # Dark grey

###################
### PERMISSIONS ###
###################

ecosystem {
  # enforce_permissions = 1
  no_donation_nag = true
  no_update_news = true
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
