###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$browser = zen-browser
# $menu = wofi --show drun


xwayland {
  force_zero_scaling = true
}

cursor {
    no_hardware_cursors = true
    use_cpu_buffer = true
  }

#################
### AUTOSTART ###
#################

exec-once = XDG_MENU_PREFIX=arch- & kbuildsycoca6 
exec-once = wl-paste --type text --watch wl-copy --primary
exec-once = walker --gapplication-service


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = EDITOR,nvim
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = WLR_RENDER_WITHOUT_EXT_BUFFER,1
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GTK_THEME,Adwaita:dark
env = GTK_APPLICATION_PREFER_DARK_THEME,1

###################
### PERMISSIONS ###
###################

# ecosystem {
#   enforce_permissions = 1
# }

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
