source = ./autostart.conf
source = ./envs.conf
source = ./input.conf
source = ./keybindings.conf
source = ./looknfeel.conf
source = ./monitors.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = size 800 600, class:.*
windowrulev2 = opacity 1 override,class:zen
windowrulev2 = opacity 1 override,title:nvim
windowrulev2 = opacity 1 override,class:mpv
windowrulev2 = opacity 1 override,title:Where Winds Meet
windowrulev2 = float,class:^(imv)$
windowrulev2 = float,class:^(mpv)$
windowrulev2 = float,class:^(waypaper)$
windowrulev2 = float,title:^(btop-float)$
windowrulev2 = float,title:^(wiremix-float)$
windowrulev2 = float,title:^(bluetui-float)$
windowrulev2 = float,title:^(impala-float)$
windowrulev2 = float,title:^(mako-float)%
