##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
  name = fullscreen
  idle_inhibit = fullscreen
  match:class= .*
}

windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = zen browser
  opacity = 1 override
  match:class = zen
}

windowrule {
  name = nvim
  opacity = 1 override
  match:title = nvim
}

windowrule {
  name = where-winds-meet
  opacity = 1 override
  match:title = Where Winds Meet
}

windowrule {
  name = imv
  float = on
  stay_focused = on
  center = on
  match:class = ^(imv)$
}

windowrule {
  name = mpv
  float = on
  stay_focused = on
  center = on
  opacity = 1 override
  match:class = ^(mpv)$
}

windowrule {
  name = dhms.terminal
  float = on
  stay_focused = on
  center = on
  size = 600 400
  match:class = ^(dhms.terminal)$
}

windowrule {
  name = satty
  float = on
  stay_focused = on
  center = on
  size = 700 500
  match:class = ^(com.gabm.satty)$
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering  = true
    allow_session_lock_restore = true
    on_focus_under_fullscreen = true
}
