##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# windowrulev2 = size 800 600, class:.*
windowrule {
  name = windowrule-3
  opacity = 1 override
  match:class = zen
}

windowrule {
  name = windowrule-4
  opacity = 1 override
  match:title = nvim
}

windowrule {
  name = windowrule-5
  opacity = 1 override
  match:class = mpv
}

windowrule {
  name = windowrule-6
  opacity = 1 override
  match:title = Where Winds Meet
}

windowrule {
  name = windowrule-7
  float = on
  match:class = ^(imv)$
}

windowrule {
  name = windowrule-8
  float = on
  match:class = ^(mpv)$
}

windowrule {
  name = windowrule-9
  float = on
  stay_focused = on
  size = 800 600
  center = on
  match:class = ^(waypaper)$
}

windowrule {
  name = windowrule-10
  float = on
  stay_focused = on
  size = 800 600
  center = on
  match:title = ^(float)$
}

windowrule {
    name = test
    stay_focused = on
    size = 800 600
    center = on
    match:float = on
  }


# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering  = true
    allow_session_lock_restore = true
    on_focus_under_fullscreen = true
}
