accent = "#A00040"
cursor = "#C80050"
foreground = "#d4d4d4"
background = "#111214"
selection_foreground = "#d4d4d4"
selection_background = "#1f2226"

color0 = "#26292f"
color1 = "#ff0055"
color2 = "#00ff66"
color3 = "#00eeff"
color4 = "#A00040"
color5 = "#bd93f9"
color6 = "#00eeff"
color7 = "#e0e0e0"
color8 = "#4d4d4d"
color9 = "#ff5588"
color10 = "#55ff99"
color11 = "#55ffff"
color12 = "#C80050"
color13 = "#e0b0ff"
color14 = "#55ffff"
color15 = "#ffffff"
