accent = "#00cc77"
cursor = "#ccffee"
foreground = "#ccffee"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#ccffee"

color0 = "#000000"
color1 = "#cccc66"
color2 = "#00ff99"
color3 = "#dddd88"
color4 = "#00cc77"
color5 = "#66ff66"
color6 = "#00ffcc"
color7 = "#aaffcc"
color8 = "#333333"
color9 = "#eeeeaa"
color10 = "#00ff99"
color11 = "#ffffdd"
color12 = "#33ff99"
color13 = "#99ff99"
color14 = "#00ffcc"
color15 = "#ccffee"
