[colors.primary]
background = "#282828"
foreground = "#dcdcdc"

[colors.cursor]
text = "#282828"
cursor = "#dcdcdc"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#dcdcdc"

[colors.search.matches]
foreground = "#282828"
background = "#dcdcdc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#a970dc"
background = "#dcdcdc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#282828"
red = "#dc2828"
green = "#28dc28"
yellow = "#dcdc28"
blue = "#2828dc"
magenta = "#dc28dc"
cyan = "#28dcdc"
white = "#dcdcdc"

[colors.bright]
black = "#363636"
red = "#e43636"
green = "#36e436"
yellow = "#e4e436"
blue = "#3636e4"
magenta = "#e436e4"
cyan = "#36e4e4"
white = "#e4e4e4"

[colors.dim]
black = "#202020"
red = "#c42020"
green = "#20c420"
yellow = "#c4c420"
blue = "#2020c4"
magenta = "#c420c4"
cyan = "#20c4c4"
white = "#c4c4c4"
