# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#dcdcdc"

# Title color for boxes
theme[title]="#9865c6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ba8de3"

# Background color of selected item in processes box
theme[selected_bg]="#a970dc"

# Foreground color of selected item in processes box
theme[selected_fg]="#dcdcdc"

# Color of inactive/disabled text
theme[inactive_fg]="#a970dc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#9865c6"

# Box outline and divider line color
theme[cpu_box]="#654384"
theme[mem_box]="#654384"
theme[net_box]="#654384"
theme[proc_box]="#654384"
theme[div_line]="#a970dc"

# Gradient for all meters and graphs
theme[temp_start]="#ba8de3"
theme[temp_mid]="#9865c6"
theme[temp_end]="#654384"


theme[cpu_start]="#ba8de3"
theme[cpu_mid]="#9865c6"
theme[cpu_end]="#654384"


theme[free_start]="#9865c6"
theme[free_mid]="#875ab0"
theme[free_end]="#875ab0"


theme[cached_start]="#875ab0"
theme[cached_mid]="#875ab0"
theme[cached_end]="#875ab0"


theme[available_start]="#ba8de3"
theme[available_mid]="#ba8de3"
theme[available_end]="#ba8de3"


theme[used_start]="#654384"
theme[used_mid]="#654384"
theme[used_end]="#654384"


theme[download_start]="#875ab0"
theme[download_mid]="#ba8de3"
theme[download_end]="#9865c6"


theme[upload_start]="#875ab0"
theme[upload_mid]="#ba8de3"
theme[upload_end]="#9865c6"