accent = "#A970DC"
cursor = "#95D6CA"
foreground = "#97B5C4"
background = "#17111C"
selection_foreground = "#17111C"
selection_background = "#97B5C4"

color0 = "#2A2136"
color1 = "#47FF54"
color2 = "#68539D"
color3 = "#514695"
color4 = "#a970dc"
color5 = "#9ED26A"
color6 = "#B42ED6"
color7 = "#DFF6F5"
color8 = "#5C5469"
color9 = "#9EDCA0"
color10 = "#7963B0"
color11 = "#34E5C4"
color12 = "#CEABD4"
color13 = "#B175BD"
color14 = "#C88CD4"
color15 = "#B19EEB"
