# Background and foreground colors
background = #282828
foreground = #dcdcdc

# Standard colors
palette = 0=#553863
palette = 1=#a970dc
palette = 2=#d4b8ee
palette = 3=#d4b8ee
palette = 4=#a970dc
palette = 5=#dca970
palette = 6=#a9dc70
palette = 7=#dcdcdc

# Bright colors
palette = 8=#553863
palette = 9=#d4b8ee
palette = 10=#70a9dc
palette = 11=#d4b8ee
palette = 12=#d4b8ee
palette = 13=#d4b8ee
palette = 14=#d4b8ee
palette = 15=#d4b8ee

# Font
font-family = JetBrainsMono Nerd Font
font-family-bold = JetBrainsMono Nerd Font
font-family-italic = JetBrainsMono Nerd Font
font-family-bold-italic = JetBrainsMono Nerd Font
font-style = Regular
font-size = 9
