general {
    ignore_empty_input = true
    disable_loading_bar = true
}

background {
    monitor =
    path = ~/.config/omarchy/current/background

    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    vibrancy = 0.1696
}

label {
    monitor =
    text = $TIME
    color = rgba(169, 112, 220, 0.8)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
  }

label {
    # Network SSID
    monitor =
    text = cmd[update:10000] echo "Network: $(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)"
    color = rgba(169, 112, 220, 0.8)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 36, 16
    halign = left
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

label {
    # Battery Status
    monitor =
    text = cmd[update:5000] echo "Battery: $(upower -i $(upower -e | grep 'BAT') | grep 'percentage' | awk '{print $2}' | tr -d '\n')"
    color = rgba(169, 112, 220, 0.8)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -36, 16
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

input-field {
    monitor =
    size = 250, 60
    position = 0, -120
    halign = center
    valign = center
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    inner_color = rgba(0, 0, 0, 0.5)
    outer_color = rgba(169, 112, 220, 0.8)
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = rgba(169, 112, 220, 0.8)

    placeholder_text = <i><span foreground="##a970dc">Enter Password</span></i>
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 16
    shadow_passes = 5
    shadow_size = 10
    fade_on_empty = false
    check_color = rgba(220, 112, 169, 0.8)
    fail_color = rgba(220, 112, 169, 0.8)
}
