background            #282828
foreground            #dcdcdc

# black
color0  #282828
color8  #363636

# red
color1  #dc2828
color9  #e43636

# green
color2  #28dc28
color10 #36e436

# yellow
color3  #dcdc28
color11 #e4e436

# blue
color4  #2828dc
color12 #3636e4

# magenta
color5  #dc28dc
color13 #e436e4

#cyan
color6  #28dcdc
color14 #36e4e4

#white
color7  #dcdcdc
color15 #e4e4e4


