[meta]
version = 1
name = "Omarchy"
description = "Follow your Omarchy system theme."
variant = "dark"
inherits = "vicinae-dark"
icon = "/home/grey/.local/share/omarchy/icon.png"

[colors.core]
background = "#282828"
foreground = "#dcdcdc"
secondary_background = "#141414"
border = "#a970dc"
accent = "#a970dc"

[colors.list.item.hover]
background = "#141414"
foreground = "#dcdcdc"

[colors.list.item.selection]
background = "#332242"
foreground = "#dcdcdc"

[colors.accents]
blue = "#2828dc"
green = "#28dc28"
magenta = "#dc28dc"
orange = "#dca928"
purple = "#a970dc"
red = "#dc2828"
yellow = "#dcdc28"
cyan = "#28dcdc"
