mode = "dark"

accent               = "#00995c"
selection            = "#12301f"
muted                = "#3b5a4a"

background           = "#0a100c"
dark_background      = "#060b08"
darker_background    = "#030503"
lighter_background   = "#15241b"

foreground           = "#a3bfae"
dark_foreground      = "#5e7d6b"
light_foreground     = "#bcd5c6"
bright_foreground    = "#dbeadd"

red                  = "#c9605f"
yellow               = "#c9ab5e"
orange               = "#cd8b52"
green                = "#7fae6f"
cyan                 = "#53b8ab"
blue                 = "#6e9fc0"
magenta              = "#b57fa3"
brown                = "#8a6d4a"

bright_red           = "#de7d7d"
bright_yellow        = "#dfca85"
bright_green         = "#93c98a"
bright_cyan          = "#7fd4c8"
bright_blue          = "#8fbfdb"
bright_magenta       = "#ca9db9"
