#!/bin/bash

export PATH="$HOME/.config/scripts:$PATH"

# Set to true when going directly to a submenu, so we can exit directly
BACK_TO_EXIT=false

back_to() {
  local parent_menu="$1"

  if [[ "$BACK_TO_EXIT" == "true" ]]; then
    exit 0
  elif [[ -n "$parent_menu" ]]; then
    "$parent_menu"
  else
    show_main_menu
  fi
}

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | walker --dmenu --width 250 --minheight 1 --maxheight 630 -p "$prompt…" "${args[@]}" 2>/dev/null
}

terminal() {
  xdg-terminal-exec --app-id=dhms.terminal "$@"
}

present_terminal() {
  floating-terminal $1
}

install() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2"
}

install_and_launch() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2 && setsid gtk-launch $3"
}

aur_install() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2"
}

aur_install_and_launch() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2 && setsid gtk-launch $3"
}

show_theme_menu() {
  walker -m menus:themesMenu --width 800 --minheight 400
}

show_install_menu() {
  case $(menu "Install" "󰣇  Package\n󰣇  AUR") in
  *Package*) terminal pkg-install ;;
  *AUR*) terminal pkg-aur-install ;;
  *) show_setup_menu ;;
  esac
}
show_setup_menu() {
  options="  Background\n󰱔  DNS\n󰉉  Install\n󱐋  Power Profile\n󰭌  Remove\n󰸌  Themes\n  Security\n  Update"

  case $(menu "Setup" "$options") in
  *Background*) waypaper ;;
  *DNS*) present_terminal setup-dns ;;
  *Install*) show_install_menu ;;
  *Power*) show_setup_power_menu ;;
  *Remove*) terminal pkg-remove ;;
  *Theme*) show_theme_menu ;;
  *Security*) show_setup_security_menu ;;
  *Update*) present_terminal pkg-update ;;
  *) show_main_menu ;;
  esac
}

show_setup_power_menu() {
  profile=$(menu "Power Profile" "$(powerprofiles-list)" "" "$(powerprofilesctl get)")

  if [[ "$profile" == "CNCLD" || -z "$profile" ]]; then
    back_to show_setup_menu
  else
    powerprofilesctl set "$profile"
  fi
}

show_setup_security_menu() {
  case $(menu "Setup" "󰈷  Fingerprint\n  Fido2") in
  *Fingerprint*) present_terminal setup-fingerprint ;;
  *Fido2*) present_terminal setup-fido2 ;;
  *) show_setup_menu ;;
  esac
}

show_system_menu() {
  case $(menu "System" "󰒲     Suspend\n    Lock\n󰜉    Reboot\n󰐥    Shutdown") in
  *Suspend*) systemctl suspend ;;
  *Lock*) hyprlock ;;
  *Reboot*) systemctl reboot ;;
  *Shutdown*) systemctl poweroff ;;
  *) back_to show_main_menu ;;
  esac
}

# show_main_menu() {
#   go_to_menu "$(menu "Go" "󰀻  Apps\n  Setup\n  System")"
# }
#
# go_to_menu() {
#   case "${1,,}" in
#   *apps*) walker -p "Launch…" ;;
#   *setup*) show_setup_menu ;;
#   *system*) show_system_menu ;;
#   esac
# }
#
# if [[ -n "$1" ]]; then
#   BACK_TO_EXIT=true
#   go_to_menu "$1"
# else
#   show_main_menu
# fi

get_all_options() {
  static="󰀻  Apps\n  Background\n󰱔  DNS\n󰉉  Install\n󰣇  Package\n󰣇  AUR\n󱐋  Power Profile\n󰭌  Remove\n󰸌  Themes\n  Security\n󰈷  Fingerprint\n  Fido2\n  Update\n󰒲     Suspend\n    Lock\n󰜉    Reboot\n󰐥    Shutdown"
  echo -e "$static"
}
execute_selection() {
  local sel="$1"
  case "$sel" in
  *Apps*) walker -p "Launch…" ;;
  *Background*) waypaper ;;
  *DNS*) present_terminal setup-dns ;;
  *Package*) terminal pkg-install ;;
  *AUR*) terminal pkg-aur-install ;;
  *Remove*) terminal pkg-remove ;;
  *Themes*) show_theme_menu ;;
  *Fingerprint*) present_terminal setup-fingerprint ;;
  *Fido2*) present_terminal setup-fido2 ;;
  *Update*) present_terminal pkg-update ;;
  *Power*) show_setup_power_menu ;;
  *Suspend*) systemctl suspend ;;
  *Lock*) hyprlock ;;
  *Reboot*) systemctl reboot ;;
  *Shutdown*) systemctl poweroff ;;
  esac
}
show_main_menu() {
  main_options="󰀻  Apps\n  Setup\n  System"
  selection=$(menu "Go" "$main_options")
  if [[ -n "$selection" ]]; then
    case "$selection" in
    *Apps*) walker -p "Launch…" ;;
    *Setup*) show_setup_menu ;;
    *System*) show_system_menu ;;
    *)
      # Treat as search query for sub-menus
      all_opts=$(get_all_options)
      filtered=$(echo -e "$all_opts" | grep -iF "$selection")
      if [[ -n "$filtered" ]]; then
        sub_selection=$(menu "Results for '$selection'" "$filtered")
        if [[ -n "$sub_selection" ]]; then
          execute_selection "$sub_selection"
        fi
      fi
      ;;
    esac
  fi
}
go_to_menu() {
  case "${1,,}" in
  *apps*) walker -p "Launch…" ;;
  *setup*) show_setup_menu ;;
  *system*) show_system_menu ;;
  esac
}
if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_main_menu
fi
