#!/bin/bash

export PATH="$HOME/.config/scripts:$PATH"

# Set to true when going directly to a submenu, so we can exit directly
BACK_TO_EXIT=false

back_to() {
  local parent_menu="$1"

  if [[ "$BACK_TO_EXIT" == "true" ]]; then
    exit 0
  elif [[ -n "$parent_menu" ]]; then
    "$parent_menu"
  else
    show_main_menu
  fi
}

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | rofi -dmenu \
    -theme ~/.config/rofi/theme.rasi \
    -theme-str 'window { width: 280px; } listview { lines: 5; }' \
    -p "$prompt…" "${args[@]}" 2>/dev/null
}

present_terminal() {
  floating-terminal $1
}

install() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2"
}

install_and_launch() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2 && setsid gtk-launch $3"
}

aur_install() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2"
}

aur_install_and_launch() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2 && setsid gtk-launch $3"
}

show_background_menu() {
  walker -m menus:backgroundSelector
}

show_theme_menu() {
  walker -m menus:themesMenu
}

show_screenrecord_menu() {
  screenrecord --stop-recording && exit 0

  case $(menu "Screenrecord" "  Without audio\n  With desktop audio\n  With desktop + microphone audio") in
  *"Without audio") screenrecord ;;
  *"With desktop audio") screenrecord --with-desktop-audio ;;
  *"With desktop + microphone audio") screenrecord --with-desktop-audio --with-microphone-audio ;;
  *) back_to show_main-menu ;;
  esac
}

show_install_menu() {
  case $(menu "Install" "󰣇  Pacman\n󰣇  AUR\n󰸌  Themes") in
  *Pacman*) present_terminal pkg-install ;;
  *AUR*) present_terminal pkg-aur-install ;;
  *Themes*) present_terminal theme-install ;;
  *) show_setup_menu ;;
  esac
}
show_setup_menu() {
  options="  Background\n󰱔  DNS\n󰉉  Install\n󱐋  Power Profile\n󰭌  Remove\n󰸌  Themes\n  Security"

  case $(menu "Setup" "$options") in
  *Background*) show_background_menu ;;
  *DNS*) present_terminal setup-dns ;;
  *Install*) show_install_menu ;;
  *Power*) show_setup_power_menu ;;
  *Remove*) present_terminal pkg-remove ;;
  *Theme*) show_theme_menu ;;
  *Security*) show_setup_security_menu ;;
  *) show_main_menu ;;
  esac
}

show_setup_power_menu() {
  profile=$(menu "Power Profile" "$(powerprofiles-list)" "" "$(powerprofilesctl get)")

  if [[ "$profile" == "CNCLD" || -z "$profile" ]]; then
    back_to show_setup_menu
  else
    powerprofilesctl set "$profile"
  fi
}

show_setup_security_menu() {
  case $(menu "Setup" "󰈷  Fingerprint\n  Fido2") in
  *Fingerprint*) present_terminal setup-fingerprint ;;
  *Fido2*) present_terminal setup-fido2 ;;
  *) show_setup_menu ;;
  esac
}

show_system_menu() {
  case $(menu "System" "󰒲    Suspend\n    Lock\n󰍃    Logout\n󰜉    Reboot\n󰐥    Shutdown") in
  *Suspend*) systemctl suspend ;;
  *lock*) pkill hyprlock && pidof hyprlock || hyprlock & ;;
  *Logout*) hyprctl dispatch exit ;;
  *Reboot*) systemctl reboot ;;
  *Shutdown*) systemctl poweroff ;;
  *) back_to show_main_menu ;;
  esac
}

show_main_menu() {
  go_to_menu "$(menu "Go" "  Update\n  Setup\n  System")"
}

go_to_menu() {
  case "${1,,}" in
  *aur*) present_terminal pkg-aur-install ;;
  *background*) show_background_menu ;;
  *dns*) present_terminal setup-dns ;;
  *fido2*) present_terminal setup-fido2 ;;
  *fingerprint*) present_terminal setup-fingerprint ;;
  *install*) show_install_menu ;;
  *lock*) pkill hyprlock && pidof hyprlock || hyprlock & ;;
  *logout*) hyprctl dispatch exit ;;
  *pacman*) present_terminal pkg-install ;;
  *power*) show_setup_power_menu ;;
  *reboot*) systemctl reboot ;;
  *remove*) present_terminal pkg-remove ;;
  *screenrecord*) show_screenrecord_menu ;;
  *security*) show_setup_security_menu ;;
  *setup*) show_setup_menu ;;
  *shutdown*) systemctl poweroff ;;
  *suspend*) systemctl suspend ;;
  *system*) show_system_menu ;;
  *themes*) show_theme_menu ;;
  *update*) present_terminal pkg-update ;;
  esac
}
if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_main_menu
fi
