#!/bin/bash

set -e

CURRENT_BRANCH=$(git -C $HOME/.dhmsDots rev-parse --abbrev-ref HEAD)
MAIN_BRANCH="main"

hyprctl dispatch tagwindow +noidle &>/dev/null || true

show-logo
sudo-keep

echo -e "\033[38;2;0;204;119mUpdating dhmsDots"
keyrings
yay -Syyu --noconfirm --cleanafter
sudo updatedb

echo -e "\033[38;2;0;204;119mGit Pull\033[0m"
git -C $HOME/.dhmsDots/ checkout "$MAIN_BRANCH"
git -C $HOME/.dhmsDots pull --autostash
git -C $HOME/.dhmsDots --no-pager diff --check || git -C $HOME/dhmsDots reset --merge

frmwr-updt
migrate-run

hyprctl dispatch tagwindow -- -noidle &>/dev/null || true
if [ -n "$CURRENT_BRANCH" ] && [ "$CURRENT_BRANCH" != "$MAIN_BRANCH" ]; then
  git -C $HOME/.dhmsDots/ checkout "$CURRENT_BRANCH"
fi
