#!/bin/bash

# EXPERIMENTAL, DON'T RUN IT YET UNTIL TESTED !!!

set -e

hyprctl dispatch tagwindow +noidle &>/dev/null || true

show-logo
sudo-keep

echo -e "\033[38;2;0;204;119mUpdating dhmsDots"
keyrings
yay -Syyu --noconfirm --cleanafter
sudo updatedb

echo -e "\033[38;2;0;204;119mGit Pull\033[0m"
git -C $HOME/.dhmsDots/ checkout main
git -C $HOME/.dhmsDots pull --autostash
git -C $HOME/.dhmsDots --no-pager diff --check || git -C $HOME/dhmsDots reset --merge

frmwr-updt
migrate-run

hyprctl dispatch tagwindow -- -noidle &>/dev/null || true
