#!/bin/bash

# EXPERIMENTAL, DON'T RUN IT YET UNTIL TESTED !!!

set -e

show-logo

echo -e "\e[32mUpdate dhms\e[0m"

git -C $HOME/dhmsDots pull --autostash
git -C $HOME/dhmsDots --no-pager diff --check || git -C $HOME/dhmsDots reset --merge

pkg-update
frmwr-updt
migration-run
