#!/bin/bash

cd ~/.dhmsDots/
migration_file="$HOME/.dhmsDots/packages/migrations/$(git log -1 --format=%cd --date=unix).sh"
touch $migration_file

if [[ "$1" != "--no-edit" ]]; then
  nvim $migration_file
fi

echo $migration_file
