#!/bin/bash
entries="󰒲     Suspend\n󰍃     Logout\n    Lock\n󰜉    Restart\n󰐥    Shutdown"

selected=$(echo -e "$entries" | walker --dmenu | awk '{print $2}')

case $selected in
Lock) pidof hyprlock || hyprlock ;;
Shutdown) systemctl poweroff ;;
Reboot) systemctl reboot ;;
Suspend) systemctl suspend ;;
Logout) ghostty --title=float -e sudo killall sddm ;;
esac
