#!/bin/bash

show-logo

HISTORY=$(makoctl history)

if [ -z "$HISTORY" ] || [ "$HISTORY" = "(null)" ]; then
  echo "You have no notification. Go get a life.."
else
  echo "$HISTORY"
fi

show-done
exit 0
