#!/bin/bash

if [[ -z $1 && $1 != "CNCLD" ]]; then
  echo "Usage: theme-set <theme-name>"
  exit 1
fi

THEMES_DIR="$HOME/.config/themes/themeLists/"
CURRENT_THEME_DIR="$HOME/.config/themes/current/theme"

THEME_NAME=$(echo "$1" | sed -E 's/<[^>]+>//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
THEME_PATH="$THEMES_DIR/$THEME_NAME"

# Check if the theme entered exists
if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
  exit 1
fi

# Update theme symlinks
ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"
